<?php

namespace Database\Seeders;

use App\Models\IceTax;
use Illuminate\Database\Seeder;

class IceTaxSeeder extends Seeder
{
    public function run(): void
    {
        $iceData = [
            [
                'product_category' => 'Cigarrillos',
                'description' => 'Cigarrillos',
                'taxable_subjects' => 'Sujetos Pasivos: Productor, Importador',
                'taxable_event' => 'Productor: Venta (primera transferencia). Importador: Importación.',
                'base_type' => 'specific',
                'specific_base_description' => 'Unidades (cigarrillos) vendidos / importados',
                'specific_rate_usd' => 0.16,
                'advalorem_rate_percent' => null,
                'exemptions' => null,
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Bebidas gaseosas con alto contenido de azúcar',
                'description' => 'Bebidas gaseosas con alto contenido de azúcar (> a 25 gramos por litro de bebida)',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'specific',
                'specific_base_description' => 'Volumen neto en un litro de bebida = (Contenido de azúcar/100) * (capacidad /1000)',
                'specific_rate_usd' => 0.18,
                'advalorem_rate_percent' => null,
                'exemptions' => 'No gravan: Bebidas gaseosas sin azúcar (u otro tipo de endulzantes no calóricos)',
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Fundas Plásticas',
                'description' => 'Fundas Plásticas',
                'taxable_subjects' => 'Sujeto Pasivo Agente de Percepción: Establecimiento de Comercio',
                'taxable_event' => 'Entrega de la funda plástica por parte del establecimiento de comercio.',
                'base_type' => 'specific',
                'specific_base_description' => 'Unidades (fundas plásticas) entregadas.',
                'specific_rate_usd' => 0.08,
                'advalorem_rate_percent' => null,
                'exemptions' => 'Exención: Estarán exentas del ICE fundas plásticas para uso industrial, agrícola, agroindustrial, de exportación, para productos congelados y las que contengan un mínimo de adición del cincuenta por ciento (50%) de materia prima reciclada post consumo, así como las fundas utilizadas como empaques primarios.',
                'reductions' => 'Rebaja: Corresponde al cincuenta por ciento (50%) en la tarifa del impuesto a los consumos especiales para fundas plásticas biodegradables y compostables.',
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Productos del tabaco',
                'description' => 'Productos del tabaco y sucedáneos o sustitutivos del tabaco en cualquier presentación',
                'taxable_subjects' => 'Sujetos Pasivos: Productor, Importador',
                'taxable_event' => 'Productor: Venta (primera transferencia). Importador: Importación.',
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 50.00,
                'exemptions' => null,
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Bebidas gaseosas contenido azúcar menor',
                'description' => 'Bebidas gaseosas con contenido de azúcar menor o igual a 25 gramos por litro de bebida; y bebidas energizantes',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 10.00,
                'exemptions' => 'No gravan: Bebidas gaseosas sin azúcar (u otro tipo de endulzantes no calóricos)',
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Perfumes y aguas de tocador',
                'description' => 'Perfumes y aguas de tocador',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 20.00,
                'exemptions' => null,
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Armas de fuego',
                'description' => 'Armas de fuego, armas deportivas y municiones',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 30.00,
                'exemptions' => 'Exención: Armas y municiones para deportistas. Las armas de fuego, sus municiones para uso de fuerza pública.',
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Focos incandescentes',
                'description' => 'Focos incandescentes',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 100.00,
                'exemptions' => 'Exención: Focos incandescentes utilizados como insumos automotrices.',
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Vehículos aéreos y acuáticos',
                'description' => 'Aviones, avionetas y helicópteros excepto aquellas destinadas al transporte comercial de pasajeros, carga y servicios; motos acuáticas, tricares, cuadrones, yates y barcos de recreo',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 10.00,
                'exemptions' => 'Exención: Los aviones, avionetas y helicópteros destinados al transporte comercial de pasajeros, carga y servicios.',
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Servicios de televisión pagada',
                'description' => 'Servicios de televisión pagada',
                'taxable_subjects' => 'Sujeto Pasivo Agente de Percepción: Prestador del servicio',
                'taxable_event' => 'Prestación del servicio',
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 15.00,
                'exemptions' => null,
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Clubes sociales',
                'description' => 'Las cuotas, membresías, afiliaciones, acciones y similares que cobren a sus miembros y usuarios los clubes sociales, para prestar sus servicios',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'advalorem',
                'specific_base_description' => null,
                'specific_rate_usd' => null,
                'advalorem_rate_percent' => 30.00,
                'exemptions' => null,
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Alcohol uso distinto',
                'description' => 'Alcohol (uso distinto a bebidas alcohólicas y farmacéuticos)',
                'taxable_subjects' => 'Sujetos Pasivos: Productor, Importador',
                'taxable_event' => 'Productor: Venta (primera transferencia). Importador: Importación.',
                'base_type' => 'both',
                'specific_base_description' => 'Litros de alcohol puro = Volumen real en litros * grado alcohólico',
                'specific_rate_usd' => 10.15,
                'advalorem_rate_percent' => 75.00,
                'exemptions' => 'Exención: Cupo anual de alcohol (nacional/importado) solicitado al SRI.',
                'reductions' => null,
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Bebidas Alcohólicas',
                'description' => 'Bebidas Alcohólicas',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'specific',
                'specific_base_description' => null,
                'specific_rate_usd' => 10.15,
                'advalorem_rate_percent' => null,
                'exemptions' => 'Exención: bebidas alcohólicas elaboradas localmente y provenientes de la fermentación alcohólica completa o parcial de productos agropecuarios cultivados en el Ecuador, adquiridos a productores que sean artesanos, microempresarios, empresas u organizaciones de la economía popular y solidaria, con ingredientes nacionales de al menos el 70%.',
                'reductions' => 'Rebaja: hasta el 50% de la tarifa específica: Bebidas alcohólicas elaboradas localmente con caña de azúcar u otros productos agropecuarios cultivados localmente, adquiridos a productores que sean artesanos, microempresas u organizaciones de la economía popular y solidaria, con al menos 70% de ingredientes nacionales.',
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Cerveza Artesanal',
                'description' => 'Cerveza Artesanal por litro de alcohol puro',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'specific',
                'specific_base_description' => null,
                'specific_rate_usd' => 1.52,
                'advalorem_rate_percent' => null,
                'exemptions' => null,
                'reductions' => 'Rebaja: hasta el 50% de la tarifa específica: cervezas elaboradas localmente con caña de azúcar u otros productos agropecuarios cultivados localmente, adquiridos a productores que sean artesanos, microempresas u organizaciones de la economía popular y solidaria, con al menos 70% de ingredientes nacionales y para nuevas marcas que se establezcan en el mercado.',
                'benefits' => null,
                'is_active' => true,
            ],
            [
                'product_category' => 'Cerveza Industrial',
                'description' => 'Cerveza Industrial por litro de alcohol puro',
                'taxable_subjects' => null,
                'taxable_event' => null,
                'base_type' => 'specific',
                'specific_base_description' => null,
                'specific_rate_usd' => 13.28,
                'advalorem_rate_percent' => null,
                'exemptions' => null,
                'reductions' => null,
                'benefits' => 'Los productos destinados a la exportación',
                'is_active' => true,
            ],
        ];

        foreach ($iceData as $ice) {
            IceTax::updateOrCreate(
                ['product_category' => $ice['product_category']],
                $ice
            );
        }
    }
}
