<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TariffCode;

class TariffCodeSeeder extends Seeder
{
    public function run(): void
    {
        $tariffCodes = [
            [
                'hs_code' => '0101210000',
                'description_en' => 'Pure-bred breeding horses',
                'description_es' => 'Caballos reproductores de raza pura',
                'base_tariff_rate' => 10.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0101291000',
                'description_en' => 'Live horses for slaughter',
                'description_es' => 'Caballos vivos para sacrificio',
                'base_tariff_rate' => 10.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0101299000',
                'description_en' => 'Other live horses',
                'description_es' => 'Otros caballos vivos',
                'base_tariff_rate' => 10.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0201100000',
                'description_en' => 'Carcasses and half-carcasses of bovine animals, fresh or chilled',
                'description_es' => 'Canales y medias canales de bovino, frescas o refrigeradas',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0201200000',
                'description_en' => 'Other cuts with bone in, of bovine animals, fresh or chilled',
                'description_es' => 'Otros cortes con hueso de bovino, frescos o refrigerados',
                'base_tariff_rate' => 12.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0201300000',
                'description_en' => 'Boneless meat of bovine animals, fresh or chilled',
                'description_es' => 'Carne deshuesada de bovino, fresca o refrigerada',
                'base_tariff_rate' => 12.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0202100000',
                'description_en' => 'Carcasses and half-carcasses of bovine animals, frozen',
                'description_es' => 'Canales y medias canales de bovino, congeladas',
                'base_tariff_rate' => 25.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0202200000',
                'description_en' => 'Other cuts with bone in, of bovine animals, frozen',
                'description_es' => 'Otros cortes con hueso de bovino, congelados',
                'base_tariff_rate' => 12.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0202300000',
                'description_en' => 'Boneless meat of bovine animals, frozen',
                'description_es' => 'Carne deshuesada de bovino, congelada',
                'base_tariff_rate' => 12.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0401100000',
                'description_en' => 'Milk and cream, not concentrated, fat content not exceeding 1%',
                'description_es' => 'Leche y nata, sin concentrar, contenido graso no superior al 1%',
                'base_tariff_rate' => 15.0,
                'iva_rate' => 0.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0401200000',
                'description_en' => 'Milk and cream, not concentrated, fat content exceeding 1% but not exceeding 6%',
                'description_es' => 'Leche y nata, sin concentrar, contenido graso superior al 1% pero no superior al 6%',
                'base_tariff_rate' => 15.0,
                'iva_rate' => 0.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0401400000',
                'description_en' => 'Milk and cream, not concentrated, fat content exceeding 6% but not exceeding 10%',
                'description_es' => 'Leche y nata, sin concentrar, contenido graso superior al 6% pero no superior al 10%',
                'base_tariff_rate' => 15.0,
                'iva_rate' => 0.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '0401500000',
                'description_en' => 'Milk and cream, not concentrated, fat content exceeding 10%',
                'description_es' => 'Leche y nata, sin concentrar, contenido graso superior al 10%',
                'base_tariff_rate' => 15.0,
                'iva_rate' => 0.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '8471300000',
                'description_en' => 'Portable automatic data processing machines',
                'description_es' => 'Máquinas automáticas para tratamiento de datos, portátiles',
                'base_tariff_rate' => 0.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '8471410000',
                'description_en' => 'Data processing machines comprising CPU and input/output units',
                'description_es' => 'Máquinas de procesamiento de datos que incluyan CPU y unidades de entrada/salida',
                'base_tariff_rate' => 0.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '8471490000',
                'description_en' => 'Other data processing machines presented in the form of systems',
                'description_es' => 'Otras máquinas de procesamiento de datos presentadas en forma de sistemas',
                'base_tariff_rate' => 0.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '8517120000',
                'description_en' => 'Telephones for cellular networks or for other wireless networks',
                'description_es' => 'Teléfonos para redes celulares o para otras redes inalámbricas',
                'base_tariff_rate' => 15.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '8517180000',
                'description_en' => 'Other telephone sets and apparatus for transmission or reception of voice',
                'description_es' => 'Otros aparatos telefónicos y aparatos para transmisión o recepción de voz',
                'base_tariff_rate' => 15.0,
                'iva_rate' => 15.0,
                'has_ice' => false,
                'is_active' => true,
            ],
            [
                'hs_code' => '8703210000',
                'description_en' => 'Motor cars with spark-ignition engine, cylinder capacity not exceeding 1000 cc',
                'description_es' => 'Automóviles con motor de encendido por chispa, cilindrada no superior a 1000 cc',
                'base_tariff_rate' => 35.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '8703220000',
                'description_en' => 'Motor cars with spark-ignition engine, cylinder capacity exceeding 1000 cc but not exceeding 1500 cc',
                'description_es' => 'Automóviles con motor de encendido por chispa, cilindrada superior a 1000 cc pero no superior a 1500 cc',
                'base_tariff_rate' => 35.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '8703230000',
                'description_en' => 'Motor cars with spark-ignition engine, cylinder capacity exceeding 1500 cc but not exceeding 3000 cc',
                'description_es' => 'Automóviles con motor de encendido por chispa, cilindrada superior a 1500 cc pero no superior a 3000 cc',
                'base_tariff_rate' => 35.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '8703240000',
                'description_en' => 'Motor cars with spark-ignition engine, cylinder capacity exceeding 3000 cc',
                'description_es' => 'Automóviles con motor de encendido por chispa, cilindrada superior a 3000 cc',
                'base_tariff_rate' => 35.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2202100000',
                'description_en' => 'Waters, including mineral waters and aerated waters, containing added sugar',
                'description_es' => 'Agua, incluidas el agua mineral y la gaseada, con adición de azúcar',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2202900000',
                'description_en' => 'Other non-alcoholic beverages',
                'description_es' => 'Otras bebidas no alcohólicas',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2402100000',
                'description_en' => 'Cigars, cheroots and cigarillos, containing tobacco',
                'description_es' => 'Puros, puritos y cigarrillos, de tabaco',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2402200000',
                'description_en' => 'Cigarettes containing tobacco',
                'description_es' => 'Cigarrillos de tabaco',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2208200000',
                'description_en' => 'Spirits obtained by distilling grape wine or grape marc',
                'description_es' => 'Aguardiente de vino o de orujo de uvas',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2208300000',
                'description_en' => 'Whiskies',
                'description_es' => 'Whisky',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2208400000',
                'description_en' => 'Rum and other spirits obtained by distilling fermented sugar-cane products',
                'description_es' => 'Ron y demás aguardientes procedentes de la destilación de productos de la caña de azúcar',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2208500000',
                'description_en' => 'Gin and Geneva',
                'description_es' => 'Ginebra',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2208600000',
                'description_en' => 'Vodka',
                'description_es' => 'Vodka',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ],
            [
                'hs_code' => '2208700000',
                'description_en' => 'Liqueurs and cordials',
                'description_es' => 'Licores',
                'base_tariff_rate' => 20.0,
                'iva_rate' => 15.0,
                'has_ice' => true,
                'is_active' => true,
            ]
        ];

        foreach ($tariffCodes as $tariffCode) {
            TariffCode::updateOrCreate(
                ['hs_code' => $tariffCode['hs_code']],
                $tariffCode
            );
        }
    }
}
